<div class="media">
	<div class="media-left">
		<a href="#">
			<img alt="64x64" class="media-object" src="https://pbs.twimg.com/profile_images/656963186675986432/tERP3ZcY.jpg" style="width: 64px; height: 64px;">
		</a>
	</div>
	<div class="media-body">
		<h4 class="media-heading">Randy Marsh</h4>
		<p>
			Randy est un géologue travaillant pour le United States Geological Survey (il est considéré comme le seul scientifique de South Park dans Combustion spontanée, mais il y en a d'autres dans la ville, comme Mephisto ou le père de Clyde). Dans À propos d'hier soir…, il est licencié, mais les épisodes suivants ne donnent pas suite à cet évènement. Dans l'épisode The Cissy (saison 18), on apprend que Randy exerce sa profession de géologue à mi-temps. En son absence, il est remplacé par la chanteuse Lorde, qui s'avère être la seconde identité de Randy.
			Sharon travaille comme secrétaire au cabinet de chirurgie esthétique comme on peut le voir dans South Park, le film : Plus long, plus grand et pas coupé mais il est aussi mentionné dans Combat d'infirmes qu'elle est la chef d'une troupe de scouts filles.
		</p>
	</div>
</div>
<div class="media">
	<div class="media-left">
		<a href="#">
			<img alt="64x64" class="media-object" src="https://pbs.twimg.com/profile_images/656963186675986432/tERP3ZcY.jpg" style="width: 64px; height: 64px;">
		</a>
	</div>
	<div class="media-body">
		<h4 class="media-heading">Randy Marsh</h4>
		<p>
			Randy est un géologue travaillant pour le United States Geological Survey (il est considéré comme le seul scientifique de South Park dans Combustion spontanée, mais il y en a d'autres dans la ville, comme Mephisto ou le père de Clyde). Dans À propos d'hier soir…, il est licencié, mais les épisodes suivants ne donnent pas suite à cet évènement. Dans l'épisode The Cissy (saison 18), on apprend que Randy exerce sa profession de géologue à mi-temps. En son absence, il est remplacé par la chanteuse Lorde, qui s'avère être la seconde identité de Randy.
			Sharon travaille comme secrétaire au cabinet de chirurgie esthétique comme on peut le voir dans South Park, le film : Plus long, plus grand et pas coupé mais il est aussi mentionné dans Combat d'infirmes qu'elle est la chef d'une troupe de scouts filles.
		</p>
	</div>
</div>
<div class="media">
	<div class="media-left">
		<a href="#">
			<img alt="64x64" class="media-object" src="https://pbs.twimg.com/profile_images/656963186675986432/tERP3ZcY.jpg" style="width: 64px; height: 64px;">
		</a>
	</div>
	<div class="media-body">
		<h4 class="media-heading">Randy Marsh</h4>
		<p>
			Randy est un géologue travaillant pour le United States Geological Survey (il est considéré comme le seul scientifique de South Park dans Combustion spontanée, mais il y en a d'autres dans la ville, comme Mephisto ou le père de Clyde). Dans À propos d'hier soir…, il est licencié, mais les épisodes suivants ne donnent pas suite à cet évènement. Dans l'épisode The Cissy (saison 18), on apprend que Randy exerce sa profession de géologue à mi-temps. En son absence, il est remplacé par la chanteuse Lorde, qui s'avère être la seconde identité de Randy.
			Sharon travaille comme secrétaire au cabinet de chirurgie esthétique comme on peut le voir dans South Park, le film : Plus long, plus grand et pas coupé mais il est aussi mentionné dans Combat d'infirmes qu'elle est la chef d'une troupe de scouts filles.
		</p>
	</div>
</div>
<div class="media">
	<div class="media-left">
		<a href="#">
			<img alt="64x64" class="media-object" src="https://pbs.twimg.com/profile_images/656963186675986432/tERP3ZcY.jpg" style="width: 64px; height: 64px;">
		</a>
	</div>
	<div class="media-body">
		<h4 class="media-heading">Randy Marsh</h4>
		<p>
			Randy est un géologue travaillant pour le United States Geological Survey (il est considéré comme le seul scientifique de South Park dans Combustion spontanée, mais il y en a d'autres dans la ville, comme Mephisto ou le père de Clyde). Dans À propos d'hier soir…, il est licencié, mais les épisodes suivants ne donnent pas suite à cet évènement. Dans l'épisode The Cissy (saison 18), on apprend que Randy exerce sa profession de géologue à mi-temps. En son absence, il est remplacé par la chanteuse Lorde, qui s'avère être la seconde identité de Randy.
			Sharon travaille comme secrétaire au cabinet de chirurgie esthétique comme on peut le voir dans South Park, le film : Plus long, plus grand et pas coupé mais il est aussi mentionné dans Combat d'infirmes qu'elle est la chef d'une troupe de scouts filles.
		</p>
	</div>
</div>
<div class="media">
	<div class="media-left">
		<a href="#">
			<img alt="64x64" class="media-object" src="https://pbs.twimg.com/profile_images/656963186675986432/tERP3ZcY.jpg" style="width: 64px; height: 64px;">
		</a>
	</div>
	<div class="media-body">
		<h4 class="media-heading">Randy Marsh</h4>
		<p>
			Randy est un géologue travaillant pour le United States Geological Survey (il est considéré comme le seul scientifique de South Park dans Combustion spontanée, mais il y en a d'autres dans la ville, comme Mephisto ou le père de Clyde). Dans À propos d'hier soir…, il est licencié, mais les épisodes suivants ne donnent pas suite à cet évènement. Dans l'épisode The Cissy (saison 18), on apprend que Randy exerce sa profession de géologue à mi-temps. En son absence, il est remplacé par la chanteuse Lorde, qui s'avère être la seconde identité de Randy.
			Sharon travaille comme secrétaire au cabinet de chirurgie esthétique comme on peut le voir dans South Park, le film : Plus long, plus grand et pas coupé mais il est aussi mentionné dans Combat d'infirmes qu'elle est la chef d'une troupe de scouts filles.
		</p>
	</div>
</div>
<div class="media">
	<div class="media-left">
		<a href="#">
			<img alt="64x64" class="media-object" src="https://pbs.twimg.com/profile_images/656963186675986432/tERP3ZcY.jpg" style="width: 64px; height: 64px;">
		</a>
	</div>
	<div class="media-body">
		<h4 class="media-heading">Randy Marsh</h4>
		<p>
			Randy est un géologue travaillant pour le United States Geological Survey (il est considéré comme le seul scientifique de South Park dans Combustion spontanée, mais il y en a d'autres dans la ville, comme Mephisto ou le père de Clyde). Dans À propos d'hier soir…, il est licencié, mais les épisodes suivants ne donnent pas suite à cet évènement. Dans l'épisode The Cissy (saison 18), on apprend que Randy exerce sa profession de géologue à mi-temps. En son absence, il est remplacé par la chanteuse Lorde, qui s'avère être la seconde identité de Randy.
			Sharon travaille comme secrétaire au cabinet de chirurgie esthétique comme on peut le voir dans South Park, le film : Plus long, plus grand et pas coupé mais il est aussi mentionné dans Combat d'infirmes qu'elle est la chef d'une troupe de scouts filles.
		</p>
	</div>
</div>
