<div class="container">
    <h2>Créer un article</h2>
    <form method="post" align="center" class="">

        <input class="form-control" type="text" name="title" placeholder="Titre de l'article" value="" required="required" />
        <label class="labelCreate">Contenu de l'article</label>
        <textarea class="form-control" cols="40" id="content" name="contenu" rows="10"></textarea>
        <label class="labelCreate">Image à uploader</label>
        <input id="input-1" type="file" class="file form-control" name="upload">

        <button type="submit" name="publish" class="btn labelCreate">Publier</button>

    </form>
</div>