<header class="page-header">
	<div class="container-fluid">
		<h1 class="text-center"><a class="" href="index.php?page=articles">Blog</a></h1>
		<nav class="navbar navbar-inverse clearfix">
			<ul class="nav navbar-nav pull-right">
				<li class=""><a class="" href="index.php?page=register">Register</a></li>
				<li class=""><a class="" href="index.php?page=login">Login</a></li>
			</ul>
		</nav>
	</div>
</header>