<div class="container row">
  <form class="col-lg-4 col-lg-offset-4" action="traitement_login.php" method="post">
    <div class="form-group">
      <label for="login">Login:</label>
      <input type="text" class="form-control input-lg" id="login" placeholder="Veuillez entrer votre login">
    </div>
    <div class="form-group">
      <label for="pwd">Mot de passe:</label>
      <input type="password" class="form-control input-lg" id="pwd" placeholder="Veuillez entrer votre mot de passe">
    </div>
    <div class="checkbox">
      <label><input type="checkbox"> Se souvenir de moi</label>
    </div>
    <button type="submit" class="btn btn-default">Entrer</button>
  </form>
</div>