<div class="row">
  <div class="col-lg-4 col-lg-offset-4">
<!--   <div><?= $error ?></div> -->
    <form class="form-horizontal" method="POST">
    <fieldset>
        <label class="">Register</label>
      <div class="control-group">
        <label class="control-label" for="username">Login (Nom d'utilisateur)</label>
        <div class="controls">
          <input type="text" id="username" name="pseudo" placeholder="" class="form-control input-lg">
          <p class="help-block">Le login peut contenir toutes les lettres et les chiffres sans espace</p>
        </div>
      </div>
   
      <div class="control-group">
        <label class="control-label" for="email">E-mail</label>
        <div class="controls">
          <input type="email" id="email" name="email" placeholder="" class="form-control input-lg">
          <p class="help-block">Veuillez entrer votre E-mail</p>
        </div>
      </div>
   
      <div class="control-group">
        <label class="control-label" for="password">Mot de passe</label>
        <div class="controls">
          <input type="password" id="password" name="password" placeholder="" class="form-control input-lg">
          <p class="help-block">Le mot de passe doit contenir au moins 6 caractères</p>
        </div>
      </div>
   
      <div class="control-group">
        <label class="control-label" for="password2">Mot de passe (Confirmation)</label>
        <div class="controls">
          <input type="password" id="password_confirm" name="password2" placeholder="" class="form-control input-lg">
          <p class="help-block">Veuillez confirmer votre mot de passe</p>
        </div>
      </div>
   
      <div class="control-group">
        <!-- Button -->
        <div class="controls">
          <button class="btn btn-success">S'enregistrer</button>
        </div>
      </div>
    </fieldset>
  </form>

  </div> 
</div>