<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Blog</title>
	<link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="public/styles/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="public/styles/style.css">
	<link rel="stylesheet" type="text/css" href="public/font-awesome/css/font-awesome.min.css">
</head>
<body>
	<?php
		require("controllers/header.php");

		require("controllers/content.php");

		require("controllers/footer.php");
	?>
	<script src="public/scripts/jquery.min.js"></script>
	<script src="public/scripts/bootstrap.min.js"></script>
</body>
</html>